apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kubescape-alerts
  namespace: kubescape
spec:
  groups:
  - name: kubescape.rules
    rules:
    - alert: KubescapeCriticalFinding
      expr: kubescape_findings_total{severity="critical"} > 0
      for: 2m
      labels:
        severity: critical
        team: security
      annotations:
        summary: "Critical Kubescape finding detected"
        description: "Kubescape detected a critical security risk"
